config/routes.rb
Rails.application.routes.draw do
  # get 'doses/new'
  # get 'doses/create'
  # get 'doses/destroy'
  # get 'new/create'
  # get 'new/destroy'
  # get 'cocktails/index'
  # get 'cocktails/show'
  # get 'cocktails/new'
  # get 'cocktails/create'
  # get 'cocktails/edit'
  # get 'cocktails/update'
  # get 'cocktails/destroy'
  # get 'cocktails/cocktail_params'
  # get 'cocktails/set_cocktail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end
end

# so this is the nesting of the routes - only the new and create routes are nested.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses
  has_many :ingredients, through: :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient_id
  validates_uniqueness_of :ingredient, scope: :cocktail_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    # @dose = Dose.new
    @doses = Dose.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
     @cocktail.delete
    redirect_to cocktails_path
  end

  private

  def cocktail_params
        params.require(:cocktail).permit(:name)

  end

  def set_cocktail
        @cocktail = Cocktail.find(params[:id])

  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    # this identifies the correct cocktail to which this new dose is connected
    # @cocktail.name = params(:name)
    @dose = Dose.new(dose_params)
    # this creates the instance of the dose through the dose params method below that is connected to the relevant cocktail
    @dose.cocktail = @cocktail
    # this connects the identified dose and the identified cocktail so that the new instance of dose can be created per the model.
    # remember that the model for dose requires three things - the cocktail, the ingrdients and the description.
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def destroy
    @dose.delete
    redirect_to cocktails_path
  end



private

def dose_params
        params.require(:dose).permit(:ingredient_id, :description)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<!-- <form action="/cocktails" method="post"></form> -->
<!-- <form action="/cocktails/1" method="patch"></form> -->

<%= simple_form_for(@cocktail) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <%= f.input :name %>
  <%#= f.hidden :description %>

</div>

  <%= f.simple_fields_for :doses do |dose_form| %>
    <%=  dose_form.input :description %>
    <%=  dose_form.input :ingredient_id, collection: Ingredient.all  %>
  <% end %>

<div class="form-actions">
  <%= f.button :submit %>
</div>

<% end %>

app/views/cocktails/cocktail_params.html.erb
<h1>Cocktails#cocktail_params</h1>
<p>Find me in app/views/cocktails/cocktail_params.html.erb</p>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

<h1>Edit or add the ingredients for this cocktail here!</h1>

<%= render  'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %>
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <p class="nav-link"><%= link_to "Add your cocktail", new_cocktail_path  %></p>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a style="font-size: 3em" class="navbar-brand mx-auto" href="#" >Welcome to our cocktail library</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">Right</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
        </ul>
    </div>
</nav>



<section class="bar" style="background-image: url(<%= image_path "bg.jpg"  %>);">
  <div class="d-flex justify-content-between">
  </div>
</section>
  <div class="container">
        <div class="cards">
          <% @cocktails.each do |cocktail| %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path "cocktailBG.jpg"  %>)">
          <%= link_to cocktail.name, cocktail_path(cocktail.id) %> </div>
          <% end %>
          </div>

  </div>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>

<h1>Add a new cocktail here!</h1>

<%= render  'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %>
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/set_cocktail.html.erb
<h1>Cocktails#set_cocktail</h1>
<p>Find me in app/views/cocktails/set_cocktail.html.erb</p>

app/views/cocktails/show.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <p class="nav-link"><%= link_to "Add your own cocktail", new_cocktail_path  %></p>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a style="font-size: 3em" class="navbar-brand mx-auto" href="#" >Your cocktail of choice</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">Right</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
        </ul>
    </div>
</nav>

<section class="bar" style="background-image: url(<%= image_path "bg.jpg"  %>);">
  <div class="d-flex justify-content-between">
  </div>
</section>

<div class="side_by_side">
  <div>
    <h3 class="show-card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path "cocktailBG.jpg"  %>)"><%= @cocktail.name %></h3>
    <%= link_to cocktail_path(@cocktail), method: :delete, data: {confirm: "Are you sure?"} do %>
      <i class="fas fa-trash-alt">      Delete it</i>
    <% end %>
  </div>

    <div class="ingredients">
      <h3>Make it</h3>
      <ul>
        <% @cocktail.doses.each do |dose| %>
          <li>
            <p><%= dose.ingredient.name %></p>
          </li>
          <li>
            <p><%= dose.description %></p>
          </li>


        <% end %>
      </ul>
    </div>
</div>



  <p><%= link_to "Think you can improve this recipe?", new_cocktail_dose_path(@cocktail) %></p>





  <p><%= link_to "Back to cocktail menu", cocktails_path %></p>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>


<!-- remember that for this form to work, it needs to work with the new dose method which is in the  -->
<!-- doses controller and that method has two variables, the @cocktails and @dose.  so cutting and pasting
this into the show view won't work unless you also change the new method in the cocktail controller so that the
view can pick up the cocktails variable.   -->
<h1><%= @cocktail.name %></h1>
<%= link_to "edit", edit_cocktail_path(@cocktail)  %>
<%= simple_form_for([@cocktail, @dose]) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="form-inputs">
 <%= f.association :ingredient %>
  <%= f.input :description %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
      <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
      <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>